<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="3" total="8" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-10T18:18:52 EDT" name="WebDriverTest" finished-at="2023-07-10T18:23:21 EDT" duration-ms="268837">
    <groups>
    </groups>
    <test started-at="2023-07-10T18:18:52 EDT" name="Test" finished-at="2023-07-10T18:23:21 EDT" duration-ms="268837">
      <class name="webDriverPractice.test.R0008TakeScreenShots">
        <test-method is-config="true" signature="setupInitialComponents()[pri:0, instance:webDriverPractice.test.R0008TakeScreenShots@6574a52c]" started-at="2023-07-10T18:18:52 EDT" name="setupInitialComponents" finished-at="2023-07-10T18:19:19 EDT" duration-ms="27132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupInitialComponents -->
        <test-method signature="selenium4testTakeScreenShot()[pri:0, instance:webDriverPractice.test.R0008TakeScreenShots@6574a52c]" started-at="2023-07-10T18:19:19 EDT" name="selenium4testTakeScreenShot" description="R0008-TC01 take screenShot of an webElement" finished-at="2023-07-10T18:19:23 EDT" duration-ms="3284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selenium4testTakeScreenShot -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:webDriverPractice.test.R0008TakeScreenShots@6574a52c]" started-at="2023-07-10T18:19:23 EDT" name="quitBrowser" finished-at="2023-07-10T18:19:40 EDT" duration-ms="17185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="setupInitialComponents()[pri:0, instance:webDriverPractice.test.R0008TakeScreenShots@6574a52c]" started-at="2023-07-10T18:19:40 EDT" name="setupInitialComponents" finished-at="2023-07-10T18:20:07 EDT" duration-ms="27399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupInitialComponents -->
        <test-method signature="testTakeScreenShot()[pri:0, instance:webDriverPractice.test.R0008TakeScreenShots@6574a52c]" started-at="2023-07-10T18:20:07 EDT" name="testTakeScreenShot" description="R0008-TC01 take screenShot of ebay Home page" finished-at="2023-07-10T18:20:19 EDT" duration-ms="11481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTakeScreenShot -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:webDriverPractice.test.R0008TakeScreenShots@6574a52c]" started-at="2023-07-10T18:20:19 EDT" name="quitBrowser" finished-at="2023-07-10T18:20:22 EDT" duration-ms="3022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- webDriverPractice.test.R0008TakeScreenShots -->
      <class name="webDriverPractice.test.R0011BrokenLinkVerification">
        <test-method retried="true" signature="testBrokenListUsingHttpsURLConnection()[pri:0, instance:webDriverPractice.test.R0011BrokenLinkVerification@4b45a2f5]" started-at="2023-07-10T18:18:52 EDT" name="testBrokenListUsingHttpsURLConnection" finished-at="2023-07-10T18:20:08 EDT" duration-ms="76271" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at webDriverPractice.test.R0011BrokenLinkVerification.testBrokenListUsingHttpsURLConnection(R0011BrokenLinkVerification.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBrokenListUsingHttpsURLConnection -->
        <test-method retried="true" signature="testBrokenListUsingHttpsURLConnection()[pri:0, instance:webDriverPractice.test.R0011BrokenLinkVerification@4b45a2f5]" started-at="2023-07-10T18:20:09 EDT" name="testBrokenListUsingHttpsURLConnection" finished-at="2023-07-10T18:20:56 EDT" duration-ms="47917" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at webDriverPractice.test.R0011BrokenLinkVerification.testBrokenListUsingHttpsURLConnection(R0011BrokenLinkVerification.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBrokenListUsingHttpsURLConnection -->
        <test-method retried="true" signature="testBrokenListUsingHttpsURLConnection()[pri:0, instance:webDriverPractice.test.R0011BrokenLinkVerification@4b45a2f5]" started-at="2023-07-10T18:20:56 EDT" name="testBrokenListUsingHttpsURLConnection" finished-at="2023-07-10T18:21:49 EDT" duration-ms="52898" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at webDriverPractice.test.R0011BrokenLinkVerification.testBrokenListUsingHttpsURLConnection(R0011BrokenLinkVerification.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBrokenListUsingHttpsURLConnection -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:webDriverPractice.test.R0011BrokenLinkVerification@4b45a2f5]" started-at="2023-07-10T18:23:20 EDT" name="quitBrowser" finished-at="2023-07-10T18:23:21 EDT" duration-ms="1059" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- webDriverPractice.test.R0011BrokenLinkVerification -->
    </test> <!-- Test -->
  </suite> <!-- WebDriverTest -->
</testng-results>
